import sys
import os
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(current_dir)
sys.path.append(os.path.dirname(current_dir))
import xml.etree.ElementTree as ET
from .ValueExpression import ValueExpression
from ..model.mapping import Mapping2Pkg


class Mapping():


    def __init__(self) -> None:
        self.ve = ValueExpression()
        self.ns = {"ns": "http://www.tracetronic.de/xml/ecu-test"}


    def parse_global_mappings(self,xam_filename):
        tree = ET.parse(xam_filename)
        root = tree.getroot()
        mapping_items = root.findall("./MAPPING-ITEM", namespaces=self.ns)
        self.ns = {"ns": ""}

        result = {} # 改为哈希
        
        for mapping_item_elem in mapping_items:

            xaccess_dict,type = self._xaccess_value(mapping_item_elem.find("./ns:XACCESS", namespaces=self.ns))
            mapping_item = Mapping2Pkg(type)

            if mapping_item_elem.find("./ns:DESCRIPTION", namespaces=self.ns) is not None:
                mapping_item.descripition = self.ve.value(mapping_item_elem.find("./ns:DESCRIPTION", namespaces=self.ns))
            
            if mapping_item_elem.find("./ns:AUTO-GENERATED", namespaces=self.ns) is not None:
                mapping_item.auto_generated = self.ve.value(mapping_item_elem.find("./ns:AUTO-GENERATED", namespaces=self.ns))
            
            if mapping_item_elem.find("./ns:CATEGORY", namespaces=self.ns) is not None:
                mapping_item.category = self.ve.value(mapping_item_elem.find("./ns:CATEGORY", namespaces=self.ns))

            mapping_item.id = self.ve.value(mapping_item_elem.find("./ns:ID", namespaces=self.ns))
            mapping_item.label = self._mapping_label(mapping_item.id)
            mapping_item.xaccess =  xaccess_dict
            mapping_item.mapping_type = type
            
            result[mapping_item.id] = mapping_item.to_dict()
        
        return result


    def parse_global_mappings_list(self,xam_filename):
        """list格式"""
        tree = ET.parse(xam_filename)
        root = tree.getroot()
        mapping_items = root.findall("./MAPPING-ITEM", namespaces=self.ns)
        self.ns = {"ns": ""}

        result = [] # 改为哈希
        
        for mapping_item_elem in mapping_items:

            xaccess_dict,type = self._xaccess_value(mapping_item_elem.find("./ns:XACCESS", namespaces=self.ns))
            mapping_item = Mapping2Pkg(type)
            if mapping_item_elem.find("./ns:DESCRIPTION", namespaces=self.ns) is not None:
                mapping_item.descripition = self.ve.value(mapping_item_elem.find("./ns:DESCRIPTION", namespaces=self.ns))
            
            if mapping_item_elem.find("./ns:AUTO-GENERATED", namespaces=self.ns) is not None:
                mapping_item.auto_generated = self.ve.value(mapping_item_elem.find("./ns:AUTO-GENERATED", namespaces=self.ns))
            
            if mapping_item_elem.find("./ns:CATEGORY", namespaces=self.ns) is not None:
                mapping_item.category = self.ve.value(mapping_item_elem.find("./ns:CATEGORY", namespaces=self.ns))

            mapping_item.id = self.ve.value(mapping_item_elem.find("./ns:ID", namespaces=self.ns))
            mapping_item.label = self._mapping_label(mapping_item.id)
            
            mapping_item.xaccess =  xaccess_dict
            mapping_item.mapping_type = type
            
            result.append(mapping_item.to_dict())
        
        return result
    

    def parse_mappings(self,xml_filename):
        """
        <MAPPING-ITEM format-rev="2" xsi:type="mappingItem">
			<ID xsi:type="string">PwrModSts_ChassisCANFD</ID>
			<XACCESS xsi:type="xaReadWriteValueVariable">
				<MAPPING-ENUM xsi:type="vtabInfoEmpty"/>
			</XACCESS>
			<AUTO-GENERATED xsi:type="boolean">False</AUTO-GENERATED>
			<CATEGORY xsi:type="string">Signal_CANFD</CATEGORY>
		</MAPPING-ITEM>
        """
        tree = ET.parse(xml_filename)
        root = tree.getroot()
        mapping_elem = root.find("./ns:MAPPING", namespaces=self.ns)
        mapping_items = mapping_elem.findall("./ns:MAPPING-ITEM", namespaces=self.ns)
        
        result = {}
        
        for mapping_item_elem in mapping_items:

            xaccess_dict,type = self._xaccess_value(mapping_item_elem.find("./ns:XACCESS", namespaces=self.ns))
            mapping_item = Mapping2Pkg(type)

            if mapping_item_elem.find("./ns:DESCRIPTION", namespaces=self.ns) is not None:
                mapping_item.descripition = self.ve.value(mapping_item_elem.find("./ns:DESCRIPTION", namespaces=self.ns))
            
            if mapping_item_elem.find("./ns:AUTO-GENERATED", namespaces=self.ns) is not None:
                mapping_item.auto_generated = self.ve.value(mapping_item_elem.find("./ns:AUTO-GENERATED", namespaces=self.ns))
            
            if mapping_item_elem.find("./ns:CATEGORY", namespaces=self.ns) is not None:
                mapping_item.category = self.ve.value(mapping_item_elem.find("./ns:CATEGORY", namespaces=self.ns))

            mapping_item.id = self.ve.value(mapping_item_elem.find("./ns:ID", namespaces=self.ns))
            mapping_item.label = self._mapping_label(mapping_item.id)
            mapping_item.xaccess =  xaccess_dict
            mapping_item.mapping_type = type
            
            result[mapping_item.id] = mapping_item
        
        return result


    def parse_mapping_item(self,mapping_item_elem):
        """
        <MAPPING-ITEM format-rev="2" xsi:type="mappingItem">
			<ID xsi:type="string">PwrModSts_ChassisCANFD</ID>
			<XACCESS xsi:type="xaReadWriteValueVariable">
				<MAPPING-ENUM xsi:type="vtabInfoEmpty"/>
			</XACCESS>
			<AUTO-GENERATED xsi:type="boolean">False</AUTO-GENERATED>
			<CATEGORY xsi:type="string">Signal_CANFD</CATEGORY>
		</MAPPING-ITEM>
        """

        xaccess_dict,type = self._xaccess_value(mapping_item_elem.find("./ns:XACCESS", namespaces=self.ns))
        mapping_item = Mapping2Pkg(type)

        if mapping_item_elem.find("./ns:DESCRIPTION", namespaces=self.ns) is not None:
            mapping_item.descripition = self.ve.value(mapping_item_elem.find("./ns:DESCRIPTION", namespaces=self.ns))
        
        if mapping_item_elem.find("./ns:AUTO-GENERATED", namespaces=self.ns) is not None:
            mapping_item.auto_generated = self.ve.value(mapping_item_elem.find("./ns:AUTO-GENERATED", namespaces=self.ns))
        
        if mapping_item_elem.find("./ns:CATEGORY", namespaces=self.ns) is not None:
            mapping_item.category = self.ve.value(mapping_item_elem.find("./ns:CATEGORY", namespaces=self.ns))

        mapping_item.id = self.ve.value(mapping_item_elem.find("./ns:ID", namespaces=self.ns))
        mapping_item.label = self._mapping_label(mapping_item.id)
        mapping_item.xaccess =  xaccess_dict
        mapping_item.mapping_type = type
        
        return mapping_item
    
    def _mapping_label(self,id):
        if id.split("/")[-1] != "Value":
            return id.split("/")[-1]
        else:
            if len(id.split("/")) > 1:
                return id.split("/")[-2]
            else:
                return id.split("/")[-1]

    
    # xaccess多种解法
    def _xaccess_value(self,elem):
        type = elem.get("{http://www.w3.org/2001/XMLSchema-instance}type")
        if type is None:
            type = elem.get("xsi_type")
        match type:
            case "xaCalibValueVariable":
                return self._xacalib_value_variable(elem),'xaCalibValueVariable'
            
            case "xaCalibVectorVariable":
                return self._xacalib_vector_variable(elem),'xaCalibVectorVariable'
            
            case "xaCalibMapVariable":
                return self._xacalib_map_variable(elem),'xaCalibMapVariable'
            
            case "xaCalibCurveVariable":
                return self._xacalib_curve_variable(elem),'xaCalibCurveVariable'

            case "xaCalibVectorElementVariable":
                return self._xacalib_vector_element_variable(elem),'xaCalibVectorElementVariable'

            case "xaMeasValueVariable":
                return self._xameas_value_variable(elem),'xaMeasValueVariable'
            
            case "xaMeasArrayElementValueVariable":
                return self._xameas_array_element_value_variable(elem),'xaMeasArrayElementValueVariable'
            
            case "xaMeasVectorVariable":
                return self._xameas_vector_variable(elem),'xaMeasVectorVariable'
            
            case "xaModelValueVariable":
                return self._xamodel_value_variable(elem),'xaModelValueVariable'
            
            case 'xaModelVectorVariable':
                return self._xamodel_vector_variable(elem),'xaModelVectorVariable'
            
            case "xaModelSignal":
                return self._xamodel_signal(elem),'xaModelSignal'
            
            case "xaReadWriteValueVariable":
                return self._xaread_write_value_variable(elem),'xaReadWriteValueVariable'
            
            case "xaBusSignalVariable":
                return self._xabus_signal_variable(elem),'xaBusSignalVariable'
            
            case "xaJob":
                return self._xajob(elem),'xaJob'
            
            case "xADiagRoutine":
                return self._xadiag_routine(elem),'xADiagRoutine'        # type不确定

            case "xADiagDid":
                return self._xadiag_did(elem),'xADiagDid'

            case "xADiagFaultMemory":
                return self.xadiag_fault_memory(elem),'xADiagFaultMemory'
            
            case "xaMissingVariable":
                return None,'xaMissingVariable'
            
            case "xaPackage":
                return  self._xa_package(elem),'xaPackage'
            
            case "xaMediaImageVariable":
                return self._xa_media_image_variable(elem),'xaMediaImageVariable'
            
            
            case "vtabInfoEmpty":
                return {}
            
            case "vtabInfoDict":
                return self._vtab_info_dict(elem)
            
            # case "string":
            #     return elem.text
            
            case _:
                print(f'出现未解析的mapping：{type}')


    def xadiag_fault_memory(self,elem):
        """
        <XACCESS xsi:type="xADiagFaultMemory">
			<ECU-KEY xsi:type="string">LZCU</ECU-KEY>
		</XACCESS>
        """
        ecu_key = None
        if elem.find("./ns:ECU-KEY", namespaces=self.ns) is not None:
            ecu_key = self.ve.value(elem.find("./ns:ECU-KEY", namespaces=self.ns))

        return {"ecu_name":ecu_key}
    

    #
    def _xadiag_did(self,elem):
        """
        <XACCESS xsi:type="xADiagDid">
			<MAPPING-ENUM xsi:type="vtabInfoEmpty"/>
			<ECU-KEY xsi:type="string">LZCU</ECU-KEY>
			<DID-NAME xsi:type="string">Driver_Window_Key_Information_3A05</DID-NAME>
		</XACCESS>
        """
        mapping_enum = {}
        ecu_key = None
        did_name = None
        if elem.find("./ns:MAPPING-ENUM", namespaces=self.ns) is not None:
            mapping_enum = self._xaccess_value(elem.find("./ns:MAPPING-ENUM", namespaces=self.ns))

        if elem.find("./ns:ECU-KEY", namespaces=self.ns) is not None:
            ecu_key = self.ve.value(elem.find("./ns:ECU-KEY", namespaces=self.ns))

        if elem.find("./ns:DID-NAME", namespaces=self.ns) is not None:
            did_name = self.ve.value(elem.find("./ns:DID-NAME", namespaces=self.ns))

        return {"enum":mapping_enum,"ecu_name":ecu_key,"did_name":did_name}


    #
    def _xadiag_routine(self,elem):
        """
        <XACCESS xsi:type="xADiagRoutine">
			<ECU-KEY xsi:type="string">LZCU</ECU-KEY>
			<ROUTINE-NAME xsi:type="string">DrvrWindow_Durability_Test_4381_Results</ROUTINE-NAME>
		</XACCESS>
        """
        ecu_key = None
        routine_name = None
        if elem.find("./ns:ECU-KEY", namespaces=self.ns) is not None:
            ecu_key = self.ve.value(elem.find("./ns:ECU-KEY", namespaces=self.ns))

        if elem.find("./ns:ROUTINE-NAME", namespaces=self.ns) is not None:
            routine_name = self.ve.value(elem.find("./ns:ROUTINE-NAME", namespaces=self.ns))

        return {"ecu_name":ecu_key,"routine_name":routine_name}
    
    
    # 
    def _xameas_vector_variable(self,elem):
        """
        <XACCESS xsi:type="xaMeasVectorVariable">
		    <MAPPING-ENUM xsi:type="vtabInfoEmpty"/>
			<ECU-KEY xsi:type="string">FunctionalECU</ECU-KEY>
			<LABEL xsi:type="string">PwrModMgrKeepAwkLog4_Glob</LABEL>
			<RASTER xsi:type="string">Port-Default</RASTER>
		</XACCESS>
        """
        ecu_key = None
        label = None
        rastep = None
        mapping_enum = {}
        if elem.find("./ns:MAPPING-ENUM", namespaces=self.ns) is not None:
            mapping_enum = self._xaccess_value(elem.find("./ns:MAPPING-ENUM", namespaces=self.ns))
        
        if elem.find("./ns:ECU-KEY", namespaces=self.ns) is not None:
            ecu_key = self.ve.value(elem.find("./ns:ECU-KEY", namespaces=self.ns))

        if elem.find("./ns:LABEL", namespaces=self.ns) is not None:
            label = self.ve.value(elem.find("./ns:LABEL", namespaces=self.ns))
        
        if elem.find("./ns:RASTER", namespaces=self.ns) is not None:
            rastep = self.ve.value(elem.find("./ns:RASTER", namespaces=self.ns))

        return {"ecu_name":ecu_key,"name":label,"rastep":rastep,"enum":mapping_enum}
        # return {'xaccess_type':"xaMeasVectorVariable","ecu_name":ecu_key,"name":label,"rastep":rastep,"enum":mapping_enum}
    
    
    # 只收
    def _xamodel_signal(self,elem):
        """
        <XACCESS format-rev="2" xsi:type="xaModelSignal">
			<MAPPING-ENUM xsi:type="vtabInfoDict">
				<VTABDICT/>
			</MAPPING-ENUM>
			<MODEL-KEY xsi:type="string">Plant model</MODEL-KEY>
			<VARIABLE-PATH xsi:type="string">Custom Devices/PROVEtechRBS/DigitalkeyCANFD_Rx/VCCD/TBOX_DKCANFD_0x2E9/TBOX2BLEMForDKSFV</VARIABLE-PATH>
		</XACCESS>
        """
        mapping_enum = {}
        model_key = None
        variable_path = None

        if elem.find("./ns:MAPPING-ENUM", namespaces=self.ns) is not None:
            mapping_enum = self._xaccess_value(elem.find("./ns:MAPPING-ENUM", namespaces=self.ns))
        
        if elem.find("./ns:MODEL-KEY", namespaces=self.ns) is not None:
            model_key = self.ve.value(elem.find("./ns:MODEL-KEY", namespaces=self.ns))

        if elem.find("./ns:VARIABLE-PATH", namespaces=self.ns) is not None:
            variable_path = self.ve.value(elem.find("./ns:VARIABLE-PATH", namespaces=self.ns))
        
        return {"enum":mapping_enum,"model_key":model_key,"variable_path":variable_path}
        # return {"xaccess_type":"xaModelSignal","enum":mapping_enum,"model_key":model_key,"variable_path":variable_path}


    # 
    def _xamodel_value_variable(self,elem):
        """
        <XACCESS format-rev="2" xsi:type="xaModelValueVariable">
			<MAPPING-ENUM xsi:type="vtabInfoDict">
				<VTABDICT/>
			</MAPPING-ENUM>
			<MODEL-KEY xsi:type="string">Plant model</MODEL-KEY>
			<VARIABLE-PATH xsi:type="string">Custom Devices/PROVEtechRBS/ZCUCANFD_Tx/FZCU/FZCU_ZCUCANFD_0x374/EcwpBdT</VARIABLE-PATH>
		</XACCESS>
        """ 
        mapping_enum = {}
        model_key = None
        variable_path = None

        if elem.find("./ns:MAPPING-ENUM", namespaces=self.ns) is not None:
            mapping_enum = self._xaccess_value(elem.find("./ns:MAPPING-ENUM", namespaces=self.ns))
        
        if elem.find("./ns:MODEL-KEY", namespaces=self.ns) is not None:
            model_key = self.ve.value(elem.find("./ns:MODEL-KEY", namespaces=self.ns))

        if elem.find("./ns:VARIABLE-PATH", namespaces=self.ns) is not None:
            variable_path = self.ve.value(elem.find("./ns:VARIABLE-PATH", namespaces=self.ns))
        
        return {"enum":mapping_enum,"model_key":model_key,"variable_path":variable_path}
        # return {"xaccess_type":"xaModelValueVariable","enum":mapping_enum,"model_key":model_key,"variable_path":variable_path}


    def _xamodel_vector_variable(self, elem):
        """
        <XACCESS format-rev="2" xsi:type="xaModelVectorVariable">
            <MAPPING-ENUM xsi:type="vtabInfoEmpty"/>
            <MODEL-KEY xsi:type="string">Plant model-1</MODEL-KEY>
            <VARIABLE-PATH xsi:type="string">diagnostic/responseList</VARIABLE-PATH>
        </XACCESS>
        """
        mapping_enum = {}
        model_key = None
        variable_path = None

        if elem.find("./ns:MAPPING-ENUM", namespaces=self.ns) is not None:
            mapping_enum = self._xaccess_value(elem.find("./ns:MAPPING-ENUM", namespaces=self.ns))
        
        if elem.find("./ns:MODEL-KEY", namespaces=self.ns) is not None:
            model_key = self.ve.value(elem.find("./ns:MODEL-KEY", namespaces=self.ns))

        if elem.find("./ns:VARIABLE-PATH", namespaces=self.ns) is not None:
            variable_path = self.ve.value(elem.find("./ns:VARIABLE-PATH", namespaces=self.ns))
        
        return {"enum":mapping_enum,"model_key":model_key,"variable_path":variable_path}

    def _xaread_write_value_variable(self,elem):
        """
        <XACCESS xsi:type="xaReadWriteValueVariable">
			<MAPPING-ENUM xsi:type="vtabInfoEmpty"/>
		</XACCESS>
        """
        mapping_enum_elem = elem.find("./ns:MAPPING-ENUM", namespaces=self.ns)

        return {"enum":self._xaccess_value(mapping_enum_elem)}
        # return {"xaccess_type":"xaReadWriteValueVariable","enum":self._xaccess_value(mapping_enum_elem)}

    ##
    def _xabus_signal_variable(self,elem):
        """
        <XACCESS format-rev="1" xsi:type="xaBusSignalVariable">
			<MAPPING-ENUM xsi:type="vtabInfoEmpty"/>
			<BUS-KEY xsi:type="string">DigitalKeyCANFD</BUS-KEY>
			<FRAME-NAME xsi:type="string">BLEM_DKCANFD_0x32D</FRAME-NAME>
			<SIGNAL-NAME xsi:type="string">BLEM2VCCDForNFCReq05</SIGNAL-NAME>
			<MANIPULATION xsi:type="signalManipulationParams">
				<DURATION style="message-count" xsi:type="manipulationDuration">
					<VALUE xsi:type="integer">0</VALUE>
				</DURATION>
			</MANIPULATION>
			<NODE-NAME xsi:type="string">BLEM</NODE-NAME>
			<PDU-NAME xsi:type="string">BLEM_DKCANFD_0x32D</PDU-NAME>
		</XACCESS>

        """
        bus_key = None
        frame_name = None
        signal_name = None
        mapping_enum = {}

        node_name = None
        pdu_name = None

        if elem.find("./ns:MAPPING-ENUM", namespaces=self.ns) is not None:
            mapping_enum = self._xaccess_value(elem.find("./ns:MAPPING-ENUM", namespaces=self.ns))
        
        if elem.find("./ns:BUS-KEY", namespaces=self.ns) is not None:
            bus_key = self.ve.value(elem.find("./ns:BUS-KEY", namespaces=self.ns))

        if elem.find("./ns:FRAME-NAME", namespaces=self.ns) is not None:
            frame_name = self.ve.value(elem.find("./ns:FRAME-NAME", namespaces=self.ns))
        
        if elem.find("./ns:SIGNAL-NAME", namespaces=self.ns) is not None:
            signal_name = self.ve.value(elem.find("./ns:SIGNAL-NAME", namespaces=self.ns))
        
        if elem.find("./ns:NODE-NAME", namespaces=self.ns) is not None:
            node_name = self.ve.value(elem.find("./ns:NODE-NAME", namespaces=self.ns))
        
        if elem.find("./ns:PDU-NAME", namespaces=self.ns) is not None:
            pdu_name = self.ve.value(elem.find("./ns:PDU-NAME", namespaces=self.ns))

        return {"bus":bus_key,"frame":frame_name,"name":signal_name,"enum":mapping_enum,"node":node_name,"pdu":pdu_name}
        # return {"xaccess_type":"xaBusSignalVariable","bus":bus_key,"frame":frame_name,"name":signal_name,"enum":mapping_enum,"node":node_name,"pdu":pdu_name}
    


    def _xacalib_value_variable(self,elem):
        """
        <XACCESS xsi:type="xaCalibValueVariable">
			<MAPPING-ENUM xsi:type="vtabInfoEmpty"/>
			<ECU-KEY xsi:type="string">FunctionalECU</ECU-KEY>
			<LABEL xsi:type="string">AdasPara_0xA</LABEL>
		</XACCESS>
        """
        mapping_enum = {}
        ecu_key = None
        label = None

        if elem.find("./ns:MAPPING-ENUM", namespaces=self.ns) is not None:
            mapping_enum = self._xaccess_value(elem.find("./ns:MAPPING-ENUM", namespaces=self.ns))
        
        if elem.find("./ns:ECU-KEY", namespaces=self.ns) is not None:
            ecu_key = self.ve.value(elem.find("./ns:ECU-KEY", namespaces=self.ns))

        if elem.find("./ns:LABEL", namespaces=self.ns) is not None:
            label = self.ve.value(elem.find("./ns:LABEL", namespaces=self.ns))
        
        return {"ecu_name":ecu_key,"name":label,"enum":mapping_enum}
        # return {"xaccess_type":"xaCalibValueVariable","ecu_name":ecu_key,"name":label,"enum":mapping_enum}

    def _xacalib_vector_variable(self,elem):
        """
        <XACCESS xsi:type="xaCalibVectorVariable">
            <MAPPING-ENUM xsi:type="vtabInfoEmpty"/>
            <ECU-KEY xsi:type="string">FunctionalECU</ECU-KEY>
            <LABEL xsi:type="string">VSL_stDrvModSelf_K</LABEL>
        </XACCESS>
        """
        mapping_enum = {}
        ecu_key = None
        label = None
        
        if elem.find("./ns:MAPPING-ENUM", namespaces=self.ns) is not None:
            mapping_enum = self._xaccess_value(elem.find("./ns:MAPPING-ENUM", namespaces=self.ns))
        
        if elem.find("./ns:ECU-KEY", namespaces=self.ns) is not None:
            ecu_key = self.ve.value(elem.find("./ns:ECU-KEY", namespaces=self.ns))
        
        if elem.find("./ns:LABEL", namespaces=self.ns) is not None:
            label = self.ve.value(elem.find("./ns:LABEL", namespaces=self.ns))
        
        return {"ecu_name":ecu_key,"name":label,"enum":mapping_enum}
        # return {"xaccess_type":"xaCalibVectorVariable","ecu_name":ecu_key,"name":label,"enum":mapping_enum}


    def _xacalib_map_variable(self, elem):
        """
        <XACCESS xsi:type="xaCalibMapVariable">
            <MAPPING-ENUM xsi:type="vtabInfoEmpty"/>
            <ECU-KEY xsi:type="string">FunctionalECU</ECU-KEY>
            <LABEL xsi:type="string">VSL_stFrntWhlSpdArbn_v</LABEL>
        </XACCESS>
        """
        mapping_enum = {}
        ecu_key = None
        label = None
        
        if elem.find("./ns:MAPPING-ENUM", namespaces=self.ns) is not None:
            mapping_enum = self._xaccess_value(elem.find("./ns:MAPPING-ENUM", namespaces=self.ns))
        
        if elem.find("./ns:ECU-KEY", namespaces=self.ns) is not None:
            ecu_key = self.ve.value(elem.find("./ns:ECU-KEY", namespaces=self.ns))
        
        if elem.find("./ns:LABEL", namespaces=self.ns) is not None:
            label = self.ve.value(elem.find("./ns:LABEL", namespaces=self.ns))
        
        return {"ecu_name":ecu_key,"name":label,"enum":mapping_enum}
        # return {"xaccess_type":"xaCalibMapVariable","ecu_name":ecu_key,"name":label,"enum":mapping_enum}
    
    def _xacalib_curve_variable(self,elem):
        """
        <XACCESS xsi:type="xaCalibCurveVariable">
            <MAPPING-ENUM xsi:type="vtabInfoEmpty"/>
            <ECU-KEY xsi:type="string">FunctionalECU</ECU-KEY>
            <LABEL xsi:type="string">WSCEA_VWhlSpFrntOffs_M</LABEL>
        </XACCESS>
        """
        mapping_enum = {}
        ecu_key = None
        label = None
        
        if elem.find("./ns:MAPPING-ENUM", namespaces=self.ns) is not None:
            mapping_enum = self._xaccess_value(elem.find("./ns:MAPPING-ENUM", namespaces=self.ns))
        
        if elem.find("./ns:ECU-KEY", namespaces=self.ns) is not None:
            ecu_key = self.ve.value(elem.find("./ns:ECU-KEY", namespaces=self.ns))
        
        if elem.find("./ns:LABEL", namespaces=self.ns) is not None:
            label = self.ve.value(elem.find("./ns:LABEL", namespaces=self.ns))

        return {"ecu_name":ecu_key,"name":label,"enum":mapping_enum}
        # return {"xaccess_type":"xaCalibCurveVariable","ecu_name":ecu_key,"name":label,"enum":mapping_enum}
    

    def _xajob(self,elem):
        """
        <XACCESS xsi:type="xaJob">
			<PORT-ID xsi:type="string">DIAG-DOIP01</PORT-ID>
			<JOB-NAME xsi:type="string">SendKey</JOB-NAME>
		</XACCESS>
        <XACCESS xsi:type="xaJob">
            <TOOL-ID xsi:type="string">INCA01</TOOL-ID>
            <JOB-NAME xsi:type="string">InitializeHardware</JOB-NAME>
        </XACCESS>
        """
        port_id = None
        tool_id = None
        job_name = None
        if elem.find("./ns:PORT-ID", namespaces=self.ns) is not None:
            port_id = self.ve.value(elem.find("./ns:PORT-ID", namespaces=self.ns))
        
        if elem.find("./ns:TOOL-ID", namespaces=self.ns) is not None:
            tool_id = self.ve.value(elem.find("./ns:TOOL-ID", namespaces=self.ns))

        if elem.find("./ns:JOB-NAME", namespaces=self.ns) is not None:
            job_name = self.ve.value(elem.find("./ns:JOB-NAME", namespaces=self.ns))

        if port_id is None:
            return {"tool_id":tool_id,"job_name":job_name}
        return {"port_id":port_id,"job_name":job_name}
        # return {"xaccess_type":"xaJob","prot_id":prot_id,"job_name":job_name}
        



    def _xameas_value_variable(self,elem):
        """
        <XACCESS xsi:type="xaMeasValueVariable">
			<MAPPING-ENUM xsi:type="vtabInfoEmpty"/>
			<ECU-KEY xsi:type="string">FunctionalECU</ECU-KEY>
			<LABEL xsi:type="string">PwrModMgrSafe_PwrModSts_out</LABEL>
			<RASTER xsi:type="string">Port-Default</RASTER>
		</XACCESS>
        """
        ecu_key = None
        label = None
        rastep = None
        mapping_enum = {}

        if elem.find("./ns:MAPPING-ENUM", namespaces=self.ns) is not None:
            mapping_enum = self._xaccess_value(elem.find("./ns:MAPPING-ENUM", namespaces=self.ns))
        
        if elem.find("./ns:ECU-KEY", namespaces=self.ns) is not None:
            ecu_key = self.ve.value(elem.find("./ns:ECU-KEY", namespaces=self.ns))

        if elem.find("./ns:LABEL", namespaces=self.ns) is not None:
            label = self.ve.value(elem.find("./ns:LABEL", namespaces=self.ns))
        
        if elem.find("./ns:RASTER", namespaces=self.ns) is not None:
            rastep = self.ve.value(elem.find("./ns:RASTER", namespaces=self.ns))

        return {"ecu_name":ecu_key,"name":label,"rastep":rastep,"enum":mapping_enum}
        # return {"xaccess_type":"xaMeasValueVariable","ecu_name":ecu_key,"name":label,"rastep":rastep,"enum":mapping_enum}



    def _xameas_array_element_value_variable(self,elem):
        """
        <XACCESS xsi:type="xaMeasArrayElementValueVariable">
			<MAPPING-ENUM xsi:type="vtabInfoEmpty"/>
			<ECU-KEY xsi:type="string">FunctionalECU</ECU-KEY>
			<LABEL xsi:type="string">PwrModMgr_DataDID_0570_ReadData_outAfterByPass</LABEL>
			<RASTER xsi:type="string">Port-Default</RASTER>
			<ARRAY-POS xsi:type="integer">0</ARRAY-POS>
		</XACCESS>
        """
        ecu_key = None
        label = None
        rastep = None
        mapping_enum = {}        
        array_pos = None
        if elem.find("./ns:MAPPING-ENUM", namespaces=self.ns) is not None:
            mapping_enum = self._xaccess_value(elem.find("./ns:MAPPING-ENUM", namespaces=self.ns))
        
        if elem.find("./ns:ECU-KEY", namespaces=self.ns) is not None:
            ecu_key = self.ve.value(elem.find("./ns:ECU-KEY", namespaces=self.ns))

        if elem.find("./ns:LABEL", namespaces=self.ns) is not None:
            label = self.ve.value(elem.find("./ns:LABEL", namespaces=self.ns))
        
        if elem.find("./ns:RASTER", namespaces=self.ns) is not None:
            rastep = self.ve.value(elem.find("./ns:RASTER", namespaces=self.ns))

        if elem.find("./ns:ARRAY-POS", namespaces=self.ns) is not None:
            array_pos = self.ve.value(elem.find("./ns:ARRAY-POS", namespaces=self.ns))
        
        # return {"xaccess_type":"xaMeasArrayElementValueVariable","ecu_name":ecu_key,"name":label,"rastep":rastep,"enum":mapping_enum,"array_pos":array_pos}
        return {"ecu_name":ecu_key,"name":label,"rastep":rastep,"enum":mapping_enum,"array_pos":array_pos}


    def _xacalib_vector_element_variable(self,elem):
        """
        <XACCESS xsi:type="xaCalibVectorElementVariable">
            <MAPPING-ENUM xsi:type="vtabInfoEmpty"/>
            <ECU-KEY xsi:type="string">FunctionalECU</ECU-KEY>
            <LABEL xsi:type="string">CKIE_ChrgnCalibVerSion_K</LABEL>
            <INDEX xsi:type="integer">2</INDEX>
        </XACCESS>
        """
        mapping_enum = {}
        ecu_key = None
        label = None
        index = None
        if elem.find("./ns:MAPPING-ENUM", namespaces=self.ns) is not None:
            mapping_enum = self._xaccess_value(elem.find("./ns:MAPPING-ENUM", namespaces=self.ns))
        
        if elem.find("./ns:ECU-KEY", namespaces=self.ns) is not None:
            ecu_key = self.ve.value(elem.find("./ns:ECU-KEY", namespaces=self.ns))
        
        if elem.find("./ns:LABEL", namespaces=self.ns) is not None:
            label = self.ve.value(elem.find("./ns:LABEL", namespaces=self.ns))
        
        if elem.find("./ns:INDEX", namespaces=self.ns) is not None:
            index = self.ve.value(elem.find("./ns:INDEX", namespaces=self.ns))
        
        return {"ecu_name":ecu_key,"name":label,"index":index,"enum":mapping_enum}
    
    def _xa_package(self, elem):
        """
        <XACCESS xsi:type="xaPackage">
            <PATH xsi:type="string">&lt;workspace.packages&gt;/SC16_防盗控制/TestStep/Set/PowerMode设置_VCCD_Number.pkg</PATH>
        </XACCESS>
        """
        path = None
        if elem.find("./ns:PATH", namespaces=self.ns) is not None:
            path = self.ve.value(elem.find("./ns:PATH", namespaces=self.ns))
        return {"path":path}
    
    def _xa_media_image_variable(self,elem):
        """
        <XACCESS xsi:type="xaMediaImageVariable">
            <NAME xsi:type="string">Image</NAME>
            <SUT xsi:type="string">CID</SUT>
            <MASK-REFERENCE/>
        </XACCESS>
        """
        name = None
        sut = None
        mask_reference = None
        if elem.find("./ns:NAME", namespaces=self.ns) is not None:
            name = self.ve.value(elem.find("./ns:NAME", namespaces=self.ns))
            
        if elem.find("./ns:SUT", namespaces=self.ns) is not None:
            sut = self.ve.value(elem.find("./ns:SUT", namespaces=self.ns))
            
        # if elem.find("./ns:MASK-REFERENCE", namespaces=self.ns) is not None:
        #     mask_reference = self.ve.value(elem.find("./ns:MASK-REFERENCE", namespaces=self.ns))
        
        return {"name":name,"sut":sut}
    

    def _vtab_info_dict(self,elem):
        """
        <MAPPING-ENUM xsi:type="vtabInfoDict">
			<VTABDICT>
				<ELEMENT dkey="0">
					<DVALUE xsi:type="string">OFF</DVALUE>
				</ELEMENT>
				<ELEMENT dkey="1">
					<DVALUE xsi:type="string">Awake</DVALUE>
				</ELEMENT>
			</VTABDICT>
		</MAPPING-ENUM>
        """
        mapping_enum = {}
        if elem.find("./ns:VTABDICT/ns:ELEMENT", namespaces=self.ns) is not None:
            for element_elem in elem.findall("./ns:VTABDICT/ns:ELEMENT", namespaces=self.ns):
                key = element_elem.get("dkey")
                value = self.ve.value(element_elem.find("./ns:DVALUE", namespaces=self.ns))
                if value is not None:
                    mapping_enum[key]= '"'+value+'"'   # 枚举量额外增加引号
        return mapping_enum

